[package]
name = "daemon_with_cli"
version = "0.1.0"
authors = ["Josh Pratt <jp10010101010000@gmail.com>"]
edition = "2018"

[[bin]]
name = "demon"
path = "src/main.rs"

[dependencies]
daemonize = "0.4.1"
